### ISSUE TITLE
Default Example sending.cc Build Failed

### ISSUE THREAD

**Issue by piyushverma** [ultravideo/uvgRTP#19] opened 2021-05-29 02:32 UTC
Thanks for shairing your great work,

I just give it a try and Example build faild here is error as below.

g++ sending.cc -luvgrtp -lpthread

media_stream.cc:(.text+0x6df): undefined reference to `uvgrtp::formats::h266::h266(uvgrtp::socket*, uvgrtp::rtp*, int)'
media_stream.cc:(.text+0x6e6): undefined reference to `typeinfo for uvgrtp::formats::h266'
media_stream.cc:(.text+0x70d): undefined reference to `uvgrtp::formats::h266::get_h266_frame_info()'
media_stream.cc:(.text+0x71a): undefined reference to `uvgrtp::formats::h266::packet_handler(void*, int, uvgrtp::frame::rtp_frame**)'
collect2: error: ld returned 1 exit

Thanks

**Comment by altonen** [comment] 2021-05-29 05:12
Hi,

what platform are you using? I'm unable to reproduce this on my Linux machine so there may be something wrong with your environment. Are you able to reproduce this if you take a fresh copy of uvgRTP, install that and then try to compile sending.cc?

**Comment by altonen** [comment] 2021-05-29 05:21
I was able to reproduce the issue if uvgRTP was compiled with QtCreator because it was missing the H.266 files. I've pushed a fix to master and it should work now.

**Comment by piyushverma** [comment] 2021-06-01 05:44
Thank you very much Altonen,

it fix the issue.

**Comment by altonen** [comment] 2021-06-01 10:49
That's good to hear, I'll close this issue then

**Closed by altonen** 2021-06-01 10:49 UTC
