### ISSUE TITLE
RTCP spam

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#139] opened 2022-07-11 16:00 UTC
Hello, 

I have pulled latest (e5fefc9) and have been experiencing the following spam from RTCP:
![image](https://user-images.githubusercontent.com/70014877/178306169-108ec322-3ced-44c6-b56a-16cdec31a378.png)

This does not seem to break any RTCP functionality, just really annoying. I commented it out for now

**Comment by jrsnen** [comment] 2022-07-12 05:52
This is probably a duplicate of #137
Also related to #126

The RTCP packet length should always be measured in 32-bit words. I'm guessing from your previous issues that you are using APP packets, but unfortunately, uvgRTP does not have padding implemented for APP or SDES messages. What this means is that if you send a message that is not measured in 32-bit words, the end gets lost at the receiver now that I implemented support for compound packets (which by the way all RTCP packets should be, including APP, see #91). 

What you should probably do in APP packets is to write the length of the payload yourself to the data (if not measurable in 32-bit words) and then pad the total packets' length with zeros to 32-bit words.

We would of course appreciate a PR for padding in uvgRTP. ;)

Closing as a duplicate of #137

**Closed by jrsnen** 2022-07-12 05:52 UTC

**Comment by jrsnen** [comment] 2022-07-12 06:10
![image](https://user-images.githubusercontent.com/6498638/178420796-0b7de8cb-f575-4beb-9004-88b031ba8075.png)
