### ISSUE TITLE
Example output parsing

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#20] opened 2021-05-30 01:24 UTC
Hello,

I am testing out the examples you've provided, and I am having a problem with parsing the output of the stream->pull_frame() function in this very first example(on the gray background): https://github.com/ultravideo/uvgRTP/tree/master/docs/examples#uvgrtp-example-codes.

I copied the code exactly, and instead of expected "Hello, world!" I am getting the following output: 
![image](https://user-images.githubusercontent.com/70014877/120088921-3d716580-c0fe-11eb-8042-7f8aaaea5d1f.png)

Is this the intended output of the payload? If so, how do I get the plain "Hello, world!"? Thank you

**Comment by altonen** [comment] 2021-05-30 04:52
Hi,

the issue is that the payload length given to `push_frame()` does not include the null byte which then causes the receiver to read beyond the bounds of `frame->payload`. Fix is easy: `size_t msg_len = strlen(message) + 1;`. I've pushed a fix to master. Thank you for the bug report.

**Closed by altonen** 2021-05-30 04:52 UTC
