### ISSUE TITLE
RTCP reports heap corruption

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#144] opened 2022-07-15 15:26 UTC
Hello, 

Originally I was trying to reproduce a different bug, which I will make a separate issue for. 

The following code (taken straight from examples, with a couple of modifications to make it run longer) produces a heap corruption (Critical error detected c0000374) if let it run long enough. Debug mode seems to be more prone to this error

```cpp

constexpr char LOCAL_INTERFACE[] = "127.0.0.1";
constexpr uint16_t LOCAL_PORT = 8888;

constexpr char REMOTE_ADDRESS[] = "127.0.0.1";
constexpr uint16_t REMOTE_PORT = 8890;

constexpr uint16_t PAYLOAD_LEN = 256;
constexpr uint16_t FRAME_RATE = 30;
constexpr uint32_t EXAMPLE_RUN_TIME_S = 30;
constexpr int SEND_TEST_PACKETS = 1000000000;
constexpr int PACKET_INTERVAL_MS = 1000 / FRAME_RATE;

/* uvgRTP calls this hook when it receives an RTCP Report
 *
 * NOTE: If application uses hook, it must also free the frame when it's done with i
 * Frame must deallocated using uvgrtp::frame::dealloc_frame() function */
void receiver_hook(uvgrtp::frame::rtcp_receiver_report* frame);
void sender_hook(uvgrtp::frame::rtcp_sender_report* frame);

void wait_until_next_frame(std::chrono::steady_clock::time_point& start, int frame_index);
void cleanup(uvgrtp::context& ctx, uvgrtp::session* local_session, uvgrtp::session* remote_session,
    uvgrtp::media_stream* send, uvgrtp::media_stream* receive);

int main(void)
{
    std::cout << "Starting uvgRTP RTCP hook example" << std::endl;

    // Creation of RTP stream. See sending example for more details
    uvgrtp::context ctx;
    uvgrtp::session* local_session = ctx.create_session(REMOTE_ADDRESS);
    uvgrtp::session* remote_session = ctx.create_session(LOCAL_INTERFACE);

    int flags = RCE_RTCP;
    uvgrtp::media_stream* local_stream = local_session->create_stream(LOCAL_PORT, REMOTE_PORT,
        RTP_FORMAT_GENERIC, flags);

    uvgrtp::media_stream* remote_stream = remote_session->create_stream(REMOTE_PORT, LOCAL_PORT,
        RTP_FORMAT_GENERIC, flags);

    // TODO: There is a bug in uvgRTP in how sender reports are implemented and this text reflects
    // that wrong thinking. Sender reports are sent by the sender

    /* In this example code, local_stream acts as the sender and because it is the only sender,
     * it does not send any RTCP frames but only receives RTCP Receiver reports from remote_stream.
     *
     * Because local_stream only sends and remote_stream only receives, we only need to install
     * receive hook for local_stream.
     *
     * By default, all media_stream that have RTCP enabled start as receivers and only if/when they
     * call push_frame() are they converted into senders. */

    if (!local_stream || local_stream->get_rtcp()->install_receiver_hook(receiver_hook) != RTP_OK)
    {
        std::cerr << "Failed to install RTCP receiver report hook" << std::endl;
        cleanup(ctx, local_session, remote_session, local_stream, remote_stream);
        return EXIT_FAILURE;
    }

    if (!remote_stream || remote_stream->get_rtcp()->install_sender_hook(sender_hook) != RTP_OK)
    {
        std::cerr << "Failed to install RTCP sender report hook" << std::endl;
        cleanup(ctx, local_session, remote_session, local_stream, remote_stream);
        return EXIT_FAILURE;
    }

    if (local_stream)
    {
        // Send dummy data so there's some RTP data to analyze
        uint8_t buffer[PAYLOAD_LEN] = { 0 };
        memset(buffer, 'a', PAYLOAD_LEN);

        memset(buffer, 0, 3);
        memset(buffer + 3, 1, 1);
        memset(buffer + 4, 1, (19 << 1)); // Intra frame

        std::chrono::steady_clock::time_point start = std::chrono::steady_clock::now();

        for (unsigned int i = 0; i < SEND_TEST_PACKETS; ++i)
        {
            if ((i + 1) % 10 == 0 || i == 0) // print every 10 frames and first
            {
                std::cout << "Sending RTP frame " << (i + 1) << "/" << SEND_TEST_PACKETS
                    << " Total data sent: " << (i + 1) * PAYLOAD_LEN << std::endl;
            }

            local_stream->push_frame((uint8_t*)buffer, PAYLOAD_LEN, RTP_NO_FLAGS);

            // send frames at constant interval to mimic a real camera stream
            std::this_thread::sleep_for(std::chrono::milliseconds(33));
        }

        std::cout << "Sending finished, total time: " <<
            (std::chrono::steady_clock::now() - start).count() / 1000000 << " ms" << std::endl;
    }

    cleanup(ctx, local_session, remote_session, local_stream, remote_stream);
    return EXIT_SUCCESS;
}

void receiver_hook(uvgrtp::frame::rtcp_receiver_report* frame)
{
    std::cout << "RTCP receiver report! ----------" << std::endl;

    for (auto& block : frame->report_blocks)
    {
        std::cout << "ssrc: " << block.ssrc << std::endl;
        std::cout << "fraction: " << static_cast<uint32_t>(block.fraction) << std::endl;
        std::cout << "lost: " << block.lost << std::endl;
        std::cout << "last_seq: " << block.last_seq << std::endl;
        std::cout << "jitter: " << block.jitter << std::endl;
        std::cout << "lsr: " << block.lsr << std::endl;
        std::cout << "dlsr (jiffies): " << uvgrtp::clock::jiffies_to_ms(block.dlsr)
            << std::endl << std::endl;
    }

    /* RTCP frames can be deallocated using delete */
    delete frame;
}

void sender_hook(uvgrtp::frame::rtcp_sender_report* frame)
{
   /* std::cout << "RTCP sender report! ----------" << std::endl;
    std::cout << "NTP msw: " << frame->sender_info.ntp_msw << std::endl;
    std::cout << "NTP lsw: " << frame->sender_info.ntp_lsw << std::endl;
    std::cout << "RTP timestamp: " << frame->sender_info.rtp_ts << std::endl;
    std::cout << "packet count: " << frame->sender_info.pkt_cnt << std::endl;
    std::cout << "byte count: " << frame->sender_info.byte_cnt << std::endl;

    for (auto& block : frame->report_blocks)
    {
        std::cout << "ssrc: " << block.ssrc << std::endl;
        std::cout << "fraction: " << static_cast<uint32_t>(block.fraction) << std::endl;
        std::cout << "lost: " << block.lost << std::endl;
        std::cout << "last_seq: " << block.last_seq << std::endl;
        std::cout << "jitter: " << block.jitter << std::endl;
        std::cout << "lsr: " << block.lsr << std::endl;
        std::cout << "dlsr (jiffies): " << uvgrtp::clock::jiffies_to_ms(block.dlsr)
            << std::endl << std::endl;
    }*/

    /* RTCP frames can be deallocated using delete */
    delete frame;
}

void wait_until_next_frame(std::chrono::steady_clock::time_point& start, int frame_index)
{
    // wait until it is time to send the next frame. Simulates a steady sending pace
    // and included only for demostration purposes since you can use uvgRTP to send
    // packets as fast as desired
    auto time_since_start = std::chrono::steady_clock::now() - start;
    auto next_frame_time = (frame_index + 1) * std::chrono::milliseconds(PACKET_INTERVAL_MS);
    if (next_frame_time > time_since_start)
    {
        std::this_thread::sleep_for(next_frame_time - time_since_start);
    }
}

void cleanup(uvgrtp::context& ctx, uvgrtp::session* local_session, uvgrtp::session* remote_session,
    uvgrtp::media_stream* send, uvgrtp::media_stream* receive)
{
    if (send)
    {
        local_session->destroy_stream(send);
    }

    if (receive)
    {
        remote_session->destroy_stream(receive);
    }

    if (local_session)
    {
        // Session must be destroyed manually
        ctx.destroy_session(local_session);
    }

    if (remote_session)
    {
        // Session must be destroyed manually
        ctx.destroy_session(remote_session);
    }
}
```

I was trying to debug this and this is the call stack:
![image](https://user-images.githubusercontent.com/70014877/179252313-bb086e81-4bb2-4db4-85fc-9c21c9c17e19.png)

I was unable to find the reason, but I am pretty sure it is related to this allocation in rtcp.cc and the following deallocations
![image](https://user-images.githubusercontent.com/70014877/179254974-27f117c2-eed7-4667-9358-0666aa993704.png)

**Comment by jrsnen** [comment] 2022-07-15 15:31
Did you include 177a0b0d838d3cf3d14213a1fe0bf73e67f0f1f7? Yesterday, I had forgotten to add APP size to the size of the RTCP packet, which would lead to this kind of problem. I pushed the fix this morning.

**Comment by wowaser** [comment] 2022-07-15 15:58
No, not yet. The f4461f6dc3642da54b762c40e691206e845c770c is messing with the flow of my existing implementation so I am sitting at 4f9bd185ce64664d3f1af8f1b48fd7c84e6b5473. I will inform you if it works when I update

**Comment by wowaser** [comment] 2022-07-18 18:50
I have doubts about this part of the code (in the uvgrtp::rtcp::generate_report()): 
Here we define how much memory we want to allocate, including how much space app packets are going to take:
![image](https://user-images.githubusercontent.com/70014877/179580412-106ee7b8-e56c-4187-a3db-4758b7d9a26e.png)

Later the memory is allocated to be of this size:
![image](https://user-images.githubusercontent.com/70014877/179580837-9aa66741-7474-4a03-afb1-312503f32463.png)

But the issue is with how much space we calculate **size_of_ready_app_packets()**. This calculation is wrong. It is just counting how many APP packets we have, not how much space they will take. 

![image](https://user-images.githubusercontent.com/70014877/179580966-6e8e3723-dd3b-4344-8119-8b6ddfdb8f12.png)
 
I tried something like this, but it didn't work:
![image](https://user-images.githubusercontent.com/70014877/179581606-d5ddfa83-4805-459c-9ee6-ed8e1be0138c.png)

**Comment by jrsnen** [comment] 2022-07-19 05:32
@wowaser In 1. You give uvgRTP 3 bytes long string and say it's 4 bytes. That is going to lead to heap corruption since uvgRTP tries to copy 4 bytes from 3 byte data.

**Comment by jrsnen** [comment] 2022-07-19 08:40
@wowaser You last suggestion for APP size was correct, pushed it to master with e35ee743e2017dfc150a2b2625f9d440caf1473b

I also found that the SDES construction did not update write_ptr correctly, which caused invalid data to be sent. This should be fixed in 1b53b6f443105cacfec7fb60a9b729520ffec40e

Does the master work now? At least my tests could receive APP now.

**Comment by wowaser** [comment] 2022-07-19 09:36
With this code 
```cpp
            if (i % 200 == 0) {
                const char* data = "ABC";
                size_t len = 4;

                local_stream->get_rtcp()->send_app_packet("APP", 1, len, (uint8_t*)data);
            }
```

It doesn't seem to be causing heap corruption, but I am getting this: 
![image](https://user-images.githubusercontent.com/70014877/179718481-da93e152-c7c0-4c10-805d-a60e7ec9eb79.png)


The majority of app packets are not getting through

**Comment by jrsnen** [comment] 2022-07-19 10:06
@wowaser I need more info to see what the problem is. I tested sending more than one APP packet and couldn't see any obvious problems. How often do you add APP for sending?

I fixed the error print, it was supposed to be debug print.

**Comment by jrsnen** [comment] 2022-07-19 10:07
The APP packets are transmitted only if there are new APP packets available for sending.

**Comment by wowaser** [comment] 2022-07-19 10:27
Did you try to run the whole program that I pasted yesterday? It sends an app packet every 200 frames, so 200*33ms = so roughly every 6.6 seconds, which is higher than RTCP interval of that example, 5 seconds

**Comment by wowaser** [comment] 2022-07-19 10:33
> Some sort of hook based API would probably be better for APP sending than the current one.

Yes, because there is currently no way to check what packets are queued for sending, right?

**Comment by jrsnen** [comment] 2022-07-19 10:37
@wowaser No, I just improved the APP rtcp test. If you send APPs less often than 5 seconds, then there will be RTCP packets that do not contain APP packets. Looking at the code you have, I can see that it uses sleep for the interval, which results in a nondeterministic send interval that can also cause problems. I'm still trying to understand what is the issue at the moment.

There is no way to check, as this part of the API has not been designed yet.

**Comment by wowaser** [comment] 2022-07-19 11:17
Can you run this example: 
https://github.com/ultravideo/uvgRTP/blob/master/examples/rtcp_hook.cc

It gives the same errors I am receiving. That is the issue I am facing. It is printing an error that is not picked up by your test suite. 

This code is not even using APP packets.

**Comment by wowaser** [comment] 2022-07-19 14:18
What about these functions?
```cpp
rtp_error_t uvgrtp::rtcp::send_app_packet(const char* name, uint8_t subtype,
    size_t payload_len, const uint8_t* payload)
{
    std::string str(name);
    rtcp_app_packet packet = { name, subtype, payload_len, payload };
    packet_mutex_.lock();
    if (!app_packets_[name].empty())
    {
        LOG_WARN("Adding a new APP packet for sending when %llu packets are waiting to be sent",
            app_packets_[name].size());
    }
    app_packets_[name].push_back(packet);
    packet_mutex_.unlock();

    return RTP_OK;
}
```
The pointer for the payload gets stored, but the packet does not get sent for some time. The original pointer for the payload goes out of scope, and now the data we get from this pointer can be anything.

Also, this function is not very safe, since the length is defined by the user:
```cpp
bool uvgrtp::construct_app_packet(uint8_t* frame, int& ptr,
    const char* name, const uint8_t* payload, size_t payload_len)
{
    memcpy(&frame[ptr], name, APP_NAME_SIZE);
    memcpy(&frame[ptr + APP_NAME_SIZE], payload, payload_len);
    ptr += APP_NAME_SIZE + payload_len;

    return true;
}
```
Bad things happen if the payload is smaller than payload_len. This actually happens when you "pad" an APP packet with 
```cpp
			if (len % 4 != 0)
			{
				len += (4 - len % 4);
			}
```

**Comment by wowaser** [comment] 2022-07-19 14:20
> @wowaser Fixed by [2ae4521](https://github.com/ultravideo/uvgRTP/commit/2ae45217bb2b5cad135c9106797dd6dc65033b61)

The rtcp example with added app packets seems to be running smoothly

**Comment by jrsnen** [comment] 2022-07-20 06:08
@wowaser Can this issue be closed?

**Comment by jrsnen** [comment] 2022-07-20 06:11
Actually, I'm just closing it. It is almost always better to open a new issue than continue an old one. Easier to follow the conversation.

**Closed by jrsnen** 2022-07-20 06:11 UTC
Labels: bug
