### ISSUE TITLE
Can't build using cmake on cygwin Windows 10

### ISSUE THREAD

**Issue by Kyu** [ultravideo/uvgRTP#8] opened 2021-02-19 22:40 UTC
Here is my process in cygwin terminal after cloning the repo

```
rocke@DESKTOP-RRF6MJJ /cygdrive/c/Users/rocke/CLionProjects/Streamer/libs/uvgRTP
$ mkdir build && cd build

rocke@DESKTOP-RRF6MJJ /cygdrive/c/Users/rocke/CLionProjects/Streamer/libs/uvgRTP/build
$ cmake ..
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/c/Users/rocke/CLionProjects/Streamer/libs/uvgRTP/build

rocke@DESKTOP-RRF6MJJ /cygdrive/c/Users/rocke/CLionProjects/Streamer/libs/uvgRTP/build
$ ninja
ninja: error: loading 'build.ninja': No such file or directory  

rocke@DESKTOP-RRF6MJJ /cygdrive/c/Users/rocke/CLionProjects/Streamer/libs/uvgRTP/build
$ ls
CMakeCache.txt  CMakeFiles  Makefile  cmake_install.cmake

# System info

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/10/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-10.2.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-10.2.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)


$ cygcheck.exe -V
cygcheck (cygwin) 3.1.7
System Checker for Cygwin
Copyright (C) 1998 - 2020 Cygwin Authors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -m
x86_64
```

I built it on an Ubuntu machine and it worked okay, unfortunately it's not the machine I develop on anymore. Did I do something wrong?

**Comment by altonen** [comment] 2021-02-20 01:22
Hello and thank you for your interest in uvgRTP!

My mistake, I wrote those instructions in a rush and missed an option you must give to CMake. You need to specify Ninja as generator if you wish to use that. i.e.:
```
cmake -GNinja ..
```

CMake obviously needs to find Ninja in order to generate build files for it. Cygwin probably has some native build tool and according to the directory contents of `/cygdrive/c/Users/rocke/CLionProjects/Streamer/libs/uvgRTP/build`, you have a Makefile there so just running `make` should work.

**Comment by Kyu** [comment] 2021-02-20 01:29
Thanks for the reply! 

I ran it with those args and now I'm getting a 

```
$ ninja
[3/43] Building CXX object CMakeFiles/uvgrtp.dir/src/hostname.cc.o
FAILED: CMakeFiles/uvgrtp.dir/src/hostname.cc.o
/usr/bin/c++.exe   -I../include -I../include/formats -I../include/zrtp -I../include/rtcp -I../include/srtp  -MD -MT CMakeFiles/uvgrtp.dir/src/hostname.cc.o -MF CMakeFiles/uvgrtp.dir/src/hostname.cc.o.d -o CMakeFiles/uvgrtp.dir/src/hostname.cc.o -c ../src/hostname.cc
In file included from ../src/hostname.cc:11:
../include/debug.hh: In function ‘void log_platform_error(const char*)’:
../include/debug.hh:85:9: error: ‘FORMAT_MESSAGE_ALLOCATE_BUFFER’ was not declared in this scope
   85 |         FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/debug.hh:85:42: error: ‘FORMAT_MESSAGE_FROM_SYSTEM’ was not declared in this scope
   85 |         FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
../include/debug.hh:85:71: error: ‘FORMAT_MESSAGE_IGNORE_INSERTS’ was not declared in this scope
   85 |         FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
      |                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/debug.hh:86:15: error: ‘WSAGetLastError’ was not declared in this scope
   86 |         NULL, WSAGetLastError(),
```  

This repeats over and over a lot, with different method/var names, so I've truncated it. Not sure why, is something missing from my environment?

**Comment by altonen** [comment] 2021-02-20 01:41
I've actually never built uvgRTP on Cygwin so I'm not surprised it doesn't work..

According to that message, it seems that the includes at the top of `include/debug.hh` don't include everything required. At least according to [1], `FORMAT_MESSAGE_ALLOCATE_BUFFER` is found in `winbase.h` but here it's clearly not found. The annoying thing is that this works fine on normal Windows so it seems to be a Cygwin-specific issue. Unfortunately I can't say what the issue is off the top of my head so I'll need to install Cygwin and try to debug this issue. I'll try to do it today.

Is using Cygwin a must for you? Can you use MinGW/regular windows with visual studio?

[1] https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage

**Comment by Kyu** [comment] 2021-02-20 01:43
I'll try VS, i'm only using Cygwin bc i'm most familiar with it on windows haha

**Comment by altonen** [comment] 2021-02-20 01:45
Okay great, please let me know how it goes.

Visual studio should work and so should MinGW as the original Windows support for uvgRTP was done using it. I guess I'll add Cygwin support to the todo list as there are people using it too.

**Comment by Kyu** [comment] 2021-02-20 01:49
Just built using VS, worked like a charm. Thank you for your time!

**Comment by altonen** [comment] 2021-02-20 01:50
Great! Closing this issue

**Closed by altonen** 2021-02-20 01:50 UTC
