### ISSUE TITLE
Can't decode in separate thread due to frames being dropped

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#166] opened 2022-09-06 12:55 UTC
I have a hook for receiving frames and the decoding is done in a separate thread. 

Ever since 2e57c2e3a7179b391c711e2bcc1e925ce68f2130 my decoder cannot decode any frames. That is, they get deallocated in the middle of the decoding process. This is because the above-mentioned commit introduces the following feature in **h26x.cc**: 
```cpp
    if (completed_ts_.find(frame->header.timestamp) != completed_ts_.end()) {
        LOG_DEBUG("Received an RTP packet belonging to a completed frame! Timestamp: %lu, seq: %u",
            frame->header.timestamp, frame->header.seq);
        return RTP_GENERIC_ERROR;
    }
```
This is the result:
![image](https://user-images.githubusercontent.com/70014877/188640058-fb06ddad-2e8b-4ed9-828b-5be64b6f29aa.png)

This happens regardless of if I produce my own timestamp for push_frame, or let it be produced automatically. The decoder can never produce an image because of frames being dropped.

However, if I comment out the above-mentioned section of the code, only about twenty frames get "duplicated" and then the execution continues normally.

**Comment by jrsnen** [comment] 2022-09-07 06:17
@wowaser Are you using master? Couple of bugs were fixed in following commits.

That check is very simple, it just drops packets belonging to timestamps that have been already been sent forward to the user for decoding. Either the timestamps for following frames are the same (there was a bug like this that got fixed) or you somehow go through the entire timestamp area in 30 seconds and hit exactly the same timestamps again (unlikely). The only way this can affect your decoding process is that you will have missing frames if there is something wrong with the timestamps.

BR, Joni

**Comment by jrsnen** [comment] 2022-09-07 08:14
I can also replicate this issue.

**Comment by jrsnen** [comment] 2022-09-07 09:53
Should be fixed by 6b883beb3fc930552fb2757707ea185e575dfb82. 

It seems the bug was caused by fef90f154c7be1ae082606d71ebdc1a1eb529ca0.

**Closed by jrsnen** 2022-09-07 09:53 UTC
Labels: critical

**Comment by wowaser** [comment] 2022-09-13 12:01
I also don't have this issue anymore

Related to this issue: after recent changes, especially regarding the flags, I still had this issue. The solution for me was to give **RTP_NO_H26X_SCL** flag to *push_frame* and everything works normally.

**Comment by jrsnen** [comment] 2022-09-15 07:15
@wowaser are you saying SCL is still bugged after 6b883beb3fc930552fb2757707ea185e575dfb82? RTP_NO_H26X_SCL disabled SCL, so it guarantees that SCL bugs won't have an effect.

**Comment by wowaser** [comment] 2022-09-15 09:59
I am not sure, but I couldn't decode, even though the stream was working properly. And the only variable was the UVGRTP library changing. It works without the flag though.
I am using Nvidia video codec sdk for enc/dec

**Comment by jrsnen** [comment] 2022-09-16 05:37
@wowaser works with the flag or without it? 

uvgRTP should work by default if user does nothing with the start codes. One additional change I made was to make the prepend start code flag the default option, meaning uvgRTP now automatically adds the start codes it removes with SCL. Maybe you were streaming with the start codes included before the change? This is probably the case if you had RTP_NO_H26X_SCL flag and didn't have any flags or code at the receiver that added start codes.

I'm just curious if there is still some sort of bug in H264 SCL?

**Comment by wowaser** [comment] 2022-09-16 11:41
Works if I provide RTP_NO_H26X_SCL flag to push_frame
