### ISSUE TITLE
RTCP crash when re-using occupied port

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#79] opened 2021-09-30 05:30 UTC
Hello, 

I have two sides of the stream, sender and receiver, with RTCP enabled. If I quit the receiver in an uncontrolled way, the sender keeps running and sending frames. When I restart the receiver the sender side crashes, I assume this is because of re-using the ports, either for stream or RTCP. This happens somewhere inside the uvgRTP library, but it is hard to pinpoint. 

Is it possible to manually check for this condition on the sender side, for example, a callback function that will re-initialize rtcp, if the reconnecting stream has a matching signature?

**Comment by jrsnen** [comment] 2021-09-30 11:45
Hi again.

Sorry to hear that you have again run into problems. I will take a look at this next week if no one else has time. The first step would probably be to create an automated test inside [rtcp tests](https://github.com/ultravideo/uvgRTP/blob/5a7d8377d15c506511b0cd416360f8d1d06ee1ef/test/tests_rtcp.cpp) to replicate this problem. If you want to help with this, it would be greatly appreciated.

**Comment by altonen** [comment] 2021-09-30 12:59
I can take a look at this if you provide code I can use to reproduce the bug.

I don't know why it crashes, it obviously shouldn't, but because UDP is connectionless, the sender has no way of knowing if the receiver is even listening to its packets. There is suppose to be some timeout mechanism which demotes senders to receivers and the sending should stop if there are no RTP packets received within some time period but I don't know if it works. If the receiver is shut down gracefully, it should send a BYE packet which should make the sender stop sending any more messages but I don't know if that relates to this bug in any way.

**Comment by jrsnen** [comment] 2022-03-01 07:01
At least one crash was fixed in 89ac6553ec5b01d0d86015304fe9b771ffe39f25. If there are more problems, feel free to reopen this issue or create a new one

**Closed by jrsnen** 2022-03-01 07:01 UTC
Labels: bug
